[package]
name = "order-taking"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
tokio = { version = "1.18.2", features = ["full"] }
futures-util = "0.3.21"
async_fn_traits = "0.1.1"